### ISSUE TITLE
Use correct Rust Pascal casing conventions

### ISSUE THREAD

**Issue by brendanzab** [Robbepop/apint#1]
Rust conventionally lowercases the tails of initialilisms in type names. For example, `Arc`, `Rc`, `RwLock`, `Cow`, `Html`, etc.  Therefore it would be more consistent to change `APInt` to `ApInt`.

**Comment by Robbepop** [comment]
Thank you for your explanation and enlightenment - I really wasn't fully aware that Rust handles names in this strict way. This will be done! :)

**Comment by brendanzab** [comment]
No, because `Int` marks the beginning of a new 'word' (even if it is shortened). See the example of `RwLock`.

**Comment by Robbepop** [comment]
Done & closed.

Thanks a lot!
