### ISSUE TITLE
Borrow-Checker (NLL) finds invalid lifetimes in constructor.rs tests

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/apint#32]
Recents NLL updates found some lifetime invalidations in `constructor.rs` unit tests.
On lines 443, 494, 527, 558 and 589 for example.

Look into the travis CI log: https://travis-ci.org/Robbepop/apint/jobs/451193349

**Comment by Robbepop** [comment]
Note this may be a compiler error: https://github.com/rust-lang/rust/issues/55806

**Comment by AaronKutch** [comment]
They closed the issue and a new beta is out try compiling again.

**Comment by Robbepop** [comment]
Yeah it works, thanks! We can close this.
