### ISSUE TITLE
Add optional #[no_std] support

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/apint#33]
The types provided by `apint` could be also available using `libcore` only.
Maybe we would need to cross-out some features but all in all it should be possible.

This issue proposes to add the `std` crate feature.
It is supposed to be enabled by default: `default = ["std"]`
Users can opt-in to use `libcore` instead of standard lib by importing `apint` without default features:
```
apint = { version = "0.2", default-features = false }
```

In this issue we can track which APIs shall be available to `#[no_std]` scenarios.

**Comment by AaronKutch** [comment]
I think in between the crate reorganization PR and the `unchecked_internals` PR I will do this and maybe fix up the error type too. Should we release a new version right after the reorganization PR or do we want to wait?

**Comment by AaronKutch** [comment]
Or I could rebase the crate reorganization PR commits to include this since it is messing with imports anyway?

**Comment by Robbepop** [comment]
> Or I could rebase the crate reorganization PR commits to include this since it is messing with imports anyway?

let us please do that in a separate PR.
as I have said I really want to keep PRs as small as possible for better reviewability and this one is already giantic.

I think it would be best to wait a bit for a release after the dust of all the new implementations and refactorings has settled down. Or what do you think?

**Comment by AaronKutch** [comment]
> I think it would be best to wait a bit for a release after the dust of all the new implementations and refactorings has settled down. Or what do you think?
Yes this is what I think

**Comment by Robbepop** [comment]
Implemented by https://github.com/Robbepop/apint/pull/50.

**Comment by Robbepop** [comment]
Implemented. Closed.
