### ISSUE TITLE
Fix clippy warnings

### ISSUE THREAD

**Issue by Robbepop** [Robbepop/apint#48]
There are tons of clippy warnings especially in the `arithmetics.rs` module. We should fix them as soon as possible since they indicate code small and potential performance regressions.

**Comment by AaronKutch** [comment]
Be sure to be using the latest nightly for now. During my development, some things were changed or even renamed.

**Comment by Robbepop** [comment]
During introduction of the new GitHub Actions based CI I just fixed all `clippy` warnings: https://github.com/Robbepop/apint/pull/64
